### PR TITLE
fix(cli): fixing CLI formatting for transactions

### LINKED ISSUE #2760: [cli] get transaction with pretty output does not return last run info
**Describe the bug**
The `tracetest get transaction --id SOME_ID -o pretty` print the following fields with empty (zero) values:
- STEPS
- LAST RUN TIME   
- LAST RUN SUCCESSES   
- LAST RUN FAILURES

**To Reproduce**
1. Create a transaction and run it
2. Using the CLI execute `tracetest get transaction --id SOME_ID -o pretty`
3. See the empty fields

**Expected behavior**
The output from the get transaction should include all the fields

**Screenshots**
Screenshot 2023-06-19 at 12 22 38

### LINKED ISSUE #2761: [cli] Steps field from list transaction is incorrect
**Describe the bug**
The `STEPS` field returned from the command `tracetest list transaction` is incorrect. It seems to be printing the number of `runs` instead of the number of `steps`.

**To Reproduce**
1. Create a transaction and run it
2. Using the CLI execute `tracetest list transaction`
3. Validate the `STEPS` field

**Expected behavior**
The `STEPS` field should include the number of steps, or we should change this field to `RUNS`.

**Scree
Screenshot 2023-06-19 at 12 26 39
nshots**

### PR DESCRIPTION
**Pull request by danielbdias**
This PR fixes the bugs reported on #2761 and #2760

Loom: https://www.loom.com/share/d3b9abf4134e41dfb46c8d6bc2a7e9c1?sid=d95b69b3-c11f-4515-937d-62e7bba69d3c

## Changes

- Fixed formatting for transactions on the flag `--output pretty`

## Fixes

- closes #2761
- closes #2760

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [x] added a test

### CODE REVIEW

File: cli/cmd/get_cmd.go [hunk 1]
```diff
@@ -29,7 +29,7 @@ var getCmd = &cobra.Command{
 			return "", err
 		}
 
-		if output == string(formatters.JSON) {
+		if output == string(formatters.JSON) || output == string(formatters.Pretty) {
```
Comment (danielbdias) [inline cli/cmd/get_cmd.go:32]: This was done to solve #2760, which was not showing values because we were not returning augmented values on get for pretty output too.

File: cli/formatters/transaction.go [hunk 2]
```diff
@@ -125,6 +125,7 @@ func (f TransactionFormatter) getTableHeader() *simpletable.Header {
 			{Text: "NAME"},
 			{Text: "VERSION"},
 			{Text: "STEPS"},
+			{Text: "RUNS"},
```
Comment (danielbdias) [inline cli/formatters/transaction.go:128]: Added to solve #2761

File: testing/cli-e2etest/helpers/table_unmarshal.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+
+	"github.com/stretchr/testify/require"
+)
+
+type tableColumnMetadata struct {
+	Name string
+	Len  int
+}
+
+func UnmarshalTable(t *testing.T, data string) []map[string]string {
```
Comment (danielbdias) [inline testing/cli-e2etest/helpers/table_unmarshal.go:15]: With this method, we can validate the table output in our tests. I'm planning to do that in future PRs.

**Review by xoscar — APPROVED** [review]
GJ @danielbdias!
