### PR TITLE
fix(server): fix test data store connection results

### LINKED ISSUE #1751: Tempo Test Connection does not return connectivity and authentication info if fetchTraces fails
**Describe the enhancement you'd like to see**
When testing a `Tempo` data store connection, if the server is not able to fetch traces I only see an error with the `fetchTraces` step. I would expect to see the full response including `connectivity` and `authentication` information.

**Additional context**
Screenshot 2022-12-28 at 12 47 07

### PR DESCRIPTION
**Pull request by jorgeepc**
This PR fixes the Test Connection result which was not including the `connectivity`/`authentication` info if the next step fails.

## Changes

- Fix test connection results

## Fixes

- fixes #1751 

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Screenshots

| Use case  | Example |
| ------------- | ------------- |
| All passed  | Screenshot 2022-12-29 at 12 32 01  |
| Fetch traces fails  |  Screenshot 2022-12-29 at 12 32 35 |
| Auth fails  |  Screenshot 2022-12-29 at 12 32 16 |
| Connectivity fails  |  Screenshot 2022-12-29 at 12 32 56 |

### CODE REVIEW

File: server/tracedb/jaegerdb.go [hunk 1]
```diff
@@ -49,9 +49,17 @@ func (jtd *jaegerTraceDB) Connect(ctx context.Context) error {
...
-	// Current implementation makes only errors to show, so if everything worked but the last
-	// step, there's no feedback that tracetest was able to ping the service and authenticate to it.
+	connectionTestResult := ConnectionTestResult{
+		ConnectivityTestResult: ConnectionTestStepResult{
+			OperationDescription: fmt.Sprintf(`Tracetest connected to "%s"`, jtd.config.Endpoint),
+		},
+		AuthenticationTestResult: ConnectionTestStepResult{
+			OperationDescription: `Tracetest managed to authenticate with Jaeger`,
+		},
+		TraceRetrivalTestResult: ConnectionTestStepResult{
```
Comment (danielbdias) [inline server/tracedb/jaegerdb.go:59]: Small thing to refactor in the future: this property name should be `TraceRetrievalTestResult` instead of `TraceRetrivalTestResult`. (I can do this, I'm planning to open a PR to solve these small typos that I've found)

**Review by danielbdias — APPROVED** [review]
:shipit:

**Review by xoscar — APPROVED** [review]
LGTM
