### PR TITLE
feat(frontend): add errors filter and minor fixes for Analyzer results

### LINKED ISSUE #2647: [Analyzer Results] UI improvements
6 UI improvements for analyzer
(In mockups changes are indicated by red arrows)

Link to mockups https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/hackathon?type=design&node-id=119%3A12394&t=iBIesn7ggxj0WJEP-1

### PR DESCRIPTION
**Pull request by jorgeepc**
This PR adds multiple UX/UI improvements to the `TraceAnalyzer` result page.

## Changes

- Update Analyzer description
- Add link to Analyzer docs from Info Tooltip
- Fix css styles for plugins
- Add Show Only Errors filter

## Fixes

- fixes #2647 

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Loom

https://www.loom.com/share/f56e08c9b6f7490586abfb445d3005fe?sid=ca4367a3-ef43-454f-90e4-6ce80c83117e

### CODE REVIEW

File: web/src/components/AnalyzerResult/CollapseIcon.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ interface IProps {
 
 const CollapseIcon = ({isCollapsed}: IProps) => {
   return (
-    <S.CollapseIconContainer>{isCollapsed ? <S.DownCollapseIcon /> : <S.UpCollapseIcon />}</S.CollapseIconContainer>
+    <S.CollapseIconContainer>{isCollapsed ? <S.UpCollapseIcon /> : <S.DownCollapseIcon />}</S.CollapseIconContainer>
```
Comment (xoscar) [inline web/src/components/AnalyzerResult/CollapseIcon.tsx:9]: What haha

File: web/src/components/AnalyzerResult/Plugins.tsx [hunk 2]
```diff
@@ -31,74 +34,87 @@ const Plugins = ({plugins, trace}: IProps) => {
...
-              </S.Column>
+    <>
+      <S.SwitchContainer>
+        <Switch checked={onlyErrors} id="only_errors_enabled" onChange={() => setOnlyErrors(prev => !prev)} />
+        <label htmlFor="only_errors_enabled">Show only errors</label>
+      </S.SwitchContainer>
+
+      <S.StyledCollapse expandIcon={({isActive = false}) => <CollapseIcon isCollapsed={isActive} />}>
+        {plugins
+          .filter(plugin => !onlyErrors || plugin.score < MAX_SCORE)
```
Comment (xoscar) [inline web/src/components/AnalyzerResult/Plugins.tsx:45]: Should we consider having a selector or service function that returns only the data we want to render? Instead of having the business logic at the component level?

File: web/src/components/AnalyzerScore/AnalyzerScore.tsx [hunk 3]
```diff
@@ -0,0 +1,25 @@
+import * as S from './AnalyzerScore.styled';
+
```
Comment (xoscar) [inline web/src/components/AnalyzerScore/AnalyzerScore.tsx:2]: We'll have to move everything to analyzer from linter, bit by bit haha

**Review by xoscar — CHANGES_REQUESTED** [review]
Hey @jorgeepc gj my dude, I left a comment about the filtering, let me know what you think!

File: web/src/components/AnalyzerResult/Plugins.tsx (hunk 2 above)
Comment (jorgeepc) [reply web/src/components/AnalyzerResult/Plugins.tsx]: Yep, good one. Done!

**Review by xoscar — APPROVED** [review]
